In [1]:
!pip install bertopic
!pip install umap-learn
!pip install hdbscan

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.1/154.1 kB 1.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 25.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.7/85.7 kB 12.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 171.5/171.5 kB 22.4 MB/s eta 0:00:00
  Using cached Cython-0.29.37-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (1.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.8/56.8 kB 7.9 MB/s eta 0:00:00
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (7

In [2]:
from google.colab import files
uploaded = files.upload()

Saving Train.csv to Train.csv


In [3]:
import pandas as pd

df = pd.read_csv('Train.csv')
data1=df['ABSTRACT']
data_for_BERTopic=data1.tolist()

In [9]:
from bertopic.representation import KeyBERTInspired
from bertopic import BERTopic

# Create your representation model
representation_model = KeyBERTInspired()

# Use the representation model in BERTopic on top of the default pipeline
topic_model = BERTopic(nr_topics=20,representation_model=representation_model)

In [10]:
topics, probabilities = topic_model.fit_transform(data_for_BERTopic)

In [11]:
data1=topic_model.get_topic_info()

In [12]:
data1

Topic  Count                                               Name  \
0      -1   3522         -1_learning_algorithms_optimization_neural   
1       0   1998            0_manifolds_manifold_curvature_elliptic   
2       1   1786  1_antiferromagnetic_magnetic_superconductivity...   
3       2   1712                  2_galaxies_galactic_galaxy_cosmic   
4       3   1570             3_neural_adversarial_learning_networks   
5       4    593             4_lasso_sparse_algorithms_optimization   
6       5    567             5_learning_reinforcement_robotic_robot   
7       6    558             6_bayesian_estimators_posterior_models   
8       7    276                  7_twitter_tweets_networks_content   
9       8    270                8_networks_nodes_communities_graphs   
10      9    264                  9_bandits_bandit_optimal_learning   
11     10    228              10_complexity_algorithms_graphs_edges   
12     11    206              11_transmit_channels_decoding_channel   
13     12    142            12_microgrid_electricity_renewable_grid   
14     13    129                    13_odometry_slam_camera_cameras   
15     14     76           14_fmri_neuroimaging_neural_neuroscience   
16     15     42        15_semantics_abstraction_programming_logics   
17     16     38                    16_players_leagues_games_sports   
18     17     15          17_melanoma_segmentation_classify_lesions   
19     18     12                 18_designs_design_optimal_criteria   

                                       Representation  \
0   [learning, algorithms, optimization, neural, o...   
1   [manifolds, manifold, curvature, elliptic, flo...   
2   [antiferromagnetic, magnetic, superconductivit...   
3   [galaxies, galactic, galaxy, cosmic, cosmologi...   
4   [neural, adversarial, learning, networks, deep...   
5   [lasso, sparse, algorithms, optimization, opti...   
6   [learning, reinforcement, robotic, robot, robo...   
7   [bayesian, estimators, posterior, models, like...   
8   [twitter, tweets, networks, content, social, r...   
9   [networks, nodes, communities, graphs, network...   
10  [bandits, bandit, optimal, learning, predictio...   
11  [complexity, algorithms, graphs, edges, vertex...   
12  [transmit, channels, decoding, channel, mimo, ...   
13  [microgrid, electricity, renewable, grid, gene...   
14  [odometry, slam, camera, cameras, pose, tracki...   
15  [fmri, neuroimaging, neural, neuroscience, bra...   
16  [semantics, abstraction, programming, logics, ...   
17  [players, leagues, games, sports, basketball, ...   
18  [melanoma, segmentation, classify, lesions, cl...   
19  [designs, design, optimal, criteria, models, a...   

                                  Representative_Docs  
0   [a most data-efficient algorithms considering ...  
1   [a geometric idea behind the method to optimal...  
2   [band topology, or global wave-function struct...  
3   [a young (~2 myr) cluster chamaeleon i was one...  
4   [humans should learn inside the continuous man...  
5   [consider a problem of estimating the low-rank...  
6   [we want to build robots that are useful insid...  
7   [approximate bayesian computation (abc) was th...  
8   [online social networks are more and more stud...  
9   [the common data mining task on networks was c...  
10  [an individual's decisions are often guided by...  
11  [given the graph $g=(v,e)$ and considering eac...  
12  [inside this paper, we develop the low-complex...  
13  [scenario generation was an important step ins...  
14  [we present the new paradigm considering real-...  
15  [brain-computer interface (bci) uses brain sig...  
16  [this article aims to achieve two goals: to sh...  
17  [during a past few years advancements inside s...  
18  [an automated method to detect and analyze a m...  
19  [inside this paper we present the new method c...

In [13]:
import numpy as np
from scipy.cluster.hierarchy import dendrogram, linkage
import matplotlib.pyplot as plt
import pandas as pd

In [14]:
!pip install transformers
!pip install torch

In [15]:
import torch
from transformers import BertTokenizer, BertModel

In [16]:
tokenizer=BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

In [17]:
def get_bert_embeddings(text):
  inputs=tokenizer(text,return_tensors='pt',padding=True,truncation=True,max_length=512)
  with torch.no_grad():
    outputs=model(**inputs)
    embeddings=outputs.last_hidden_state[:,0,:].numpy()
    return embeddings
def list_to_string(lst):
    """
    Convert a list of strings to a single string separated by spaces.

    Parameters:
    lst (list): List of strings

    Returns:
    str: A single string containing all elements from the list separated by spaces
    """
    return " ".join(lst)
print(get_bert_embeddings(list_to_string(data1['Representation'][0])))


[[-2.35518619e-01  1.21986315e-01 -1.33598268e-01  2.05507770e-01
  -1.18577607e-01  7.33146146e-02  4.46068794e-02  3.98549706e-01
  -3.68138999e-01 -3.01099747e-01 -1.34074181e-01  2.25091860e-01
   8.15175846e-03  7.98186585e-02 -5.46669140e-02  6.25713840e-02
  -3.37201506e-01  4.80864823e-01  4.78400022e-01 -2.06622705e-01
  -4.67588454e-02 -4.70916420e-01 -1.86488107e-01 -2.12192819e-01
  -3.73626947e-01 -7.56911635e-02 -1.06664047e-01 -5.30707315e-02
   2.79004186e-01 -1.09186266e-02 -3.25509429e-01  3.80457222e-01
  -1.70521498e-01 -3.13157886e-01  5.06032288e-01 -1.21602908e-01
   2.42973000e-01 -3.45494330e-01  8.34816322e-02  1.29381493e-02
   9.63905007e-02  5.66699468e-02  6.44215941e-01  3.37131098e-02
  -2.06878126e-01 -3.05675894e-01 -2.70882607e+00 -3.52741331e-01
  -2.00087339e-01 -3.08317274e-01 -2.47935772e-01  3.14058483e-01
   2.54194051e-01  2.40190238e-01  5.89538105e-02  2.57942170e-01
   4.43013370e-01  1.22288451e-01  5.60164332e-01  4.84944612e-01
  -1.60553

In [19]:
repr=data1['Representation']
def list_to_string(lst):
    return " ".join(lst)

# Convert lists to strings
keywords_strings = [list_to_string(lst) for lst in repr]

# Create a new DataFrame with the converted strings
new_df = pd.DataFrame(keywords_strings, columns=['Keywords_String'])

In [20]:
new_df

Keywords_String
0   learning algorithms optimization neural optima...
1   manifolds manifold curvature elliptic flows no...
2   antiferromagnetic magnetic superconductivity s...
3   galaxies galactic galaxy cosmic cosmological s...
4   neural adversarial learning networks deep reco...
5   lasso sparse algorithms optimization optimal l...
6   learning reinforcement robotic robot robots pl...
7   bayesian estimators posterior models likelihoo...
8   twitter tweets networks content social recomme...
9   networks nodes communities graphs network clus...
10  bandits bandit optimal learning prediction rew...
11  complexity algorithms graphs edges vertex grap...
12  transmit channels decoding channel mimo antenn...
13  microgrid electricity renewable grid generator...
14  odometry slam camera cameras pose tracking 3d ...
15  fmri neuroimaging neural neuroscience brain co...
16  semantics abstraction programming logics logic...
17  players leagues games sports basketball soccer...
18  melanoma segmentation classify lesions classif...
19  designs design optimal criteria models algorit...

In [21]:
data1

Topic  Count                                               Name  \
0      -1   3522         -1_learning_algorithms_optimization_neural   
1       0   1998            0_manifolds_manifold_curvature_elliptic   
2       1   1786  1_antiferromagnetic_magnetic_superconductivity...   
3       2   1712                  2_galaxies_galactic_galaxy_cosmic   
4       3   1570             3_neural_adversarial_learning_networks   
5       4    593             4_lasso_sparse_algorithms_optimization   
6       5    567             5_learning_reinforcement_robotic_robot   
7       6    558             6_bayesian_estimators_posterior_models   
8       7    276                  7_twitter_tweets_networks_content   
9       8    270                8_networks_nodes_communities_graphs   
10      9    264                  9_bandits_bandit_optimal_learning   
11     10    228              10_complexity_algorithms_graphs_edges   
12     11    206              11_transmit_channels_decoding_channel   
13     12    142            12_microgrid_electricity_renewable_grid   
14     13    129                    13_odometry_slam_camera_cameras   
15     14     76           14_fmri_neuroimaging_neural_neuroscience   
16     15     42        15_semantics_abstraction_programming_logics   
17     16     38                    16_players_leagues_games_sports   
18     17     15          17_melanoma_segmentation_classify_lesions   
19     18     12                 18_designs_design_optimal_criteria   

                                       Representation  \
0   [learning, algorithms, optimization, neural, o...   
1   [manifolds, manifold, curvature, elliptic, flo...   
2   [antiferromagnetic, magnetic, superconductivit...   
3   [galaxies, galactic, galaxy, cosmic, cosmologi...   
4   [neural, adversarial, learning, networks, deep...   
5   [lasso, sparse, algorithms, optimization, opti...   
6   [learning, reinforcement, robotic, robot, robo...   
7   [bayesian, estimators, posterior, models, like...   
8   [twitter, tweets, networks, content, social, r...   
9   [networks, nodes, communities, graphs, network...   
10  [bandits, bandit, optimal, learning, predictio...   
11  [complexity, algorithms, graphs, edges, vertex...   
12  [transmit, channels, decoding, channel, mimo, ...   
13  [microgrid, electricity, renewable, grid, gene...   
14  [odometry, slam, camera, cameras, pose, tracki...   
15  [fmri, neuroimaging, neural, neuroscience, bra...   
16  [semantics, abstraction, programming, logics, ...   
17  [players, leagues, games, sports, basketball, ...   
18  [melanoma, segmentation, classify, lesions, cl...   
19  [designs, design, optimal, criteria, models, a...   

                                  Representative_Docs  
0   [a most data-efficient algorithms considering ...  
1   [a geometric idea behind the method to optimal...  
2   [band topology, or global wave-function struct...  
3   [a young (~2 myr) cluster chamaeleon i was one...  
4   [humans should learn inside the continuous man...  
5   [consider a problem of estimating the low-rank...  
6   [we want to build robots that are useful insid...  
7   [approximate bayesian computation (abc) was th...  
8   [online social networks are more and more stud...  
9   [the common data mining task on networks was c...  
10  [an individual's decisions are often guided by...  
11  [given the graph $g=(v,e)$ and considering eac...  
12  [inside this paper, we develop the low-complex...  
13  [scenario generation was an important step ins...  
14  [we present the new paradigm considering real-...  
15  [brain-computer interface (bci) uses brain sig...  
16  [this article aims to achieve two goals: to sh...  
17  [during a past few years advancements inside s...  
18  [an automated method to detect and analyze a m...  
19  [inside this paper we present the new method c...

In [24]:
new_df=new_df.drop(0)

In [25]:
new_df

Keywords_String
1   manifolds manifold curvature elliptic flows no...
2   antiferromagnetic magnetic superconductivity s...
3   galaxies galactic galaxy cosmic cosmological s...
4   neural adversarial learning networks deep reco...
5   lasso sparse algorithms optimization optimal l...
6   learning reinforcement robotic robot robots pl...
7   bayesian estimators posterior models likelihoo...
8   twitter tweets networks content social recomme...
9   networks nodes communities graphs network clus...
10  bandits bandit optimal learning prediction rew...
11  complexity algorithms graphs edges vertex grap...
12  transmit channels decoding channel mimo antenn...
13  microgrid electricity renewable grid generator...
14  odometry slam camera cameras pose tracking 3d ...
15  fmri neuroimaging neural neuroscience brain co...
16  semantics abstraction programming logics logic...
17  players leagues games sports basketball soccer...
18  melanoma segmentation classify lesions classif...
19  designs design optimal criteria models algorit...

In [34]:
import pandas as pd
import numpy as np
import umap
from transformers import BertTokenizer, BertModel
import torch

# Initialize BERT tokenizer and model
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

# Function to get BERT embeddings
def get_bert_embeddings(text):
    # Tokenize input text and get embeddings
    inputs = tokenizer(text, return_tensors='pt', padding=True, truncation=True, max_length=128)
    with torch.no_grad():
        outputs = model(**inputs)
    embeddings = outputs.last_hidden_state.mean(dim=1).numpy()  # Mean pooling of embeddings
    return embeddings

# Sample DataFrame
df = pd.DataFrame(new_df)

# Get BERT embeddings for each row in 'Keywords_String' column
embeddings_list = [get_bert_embeddings(text) for text in df['Keywords_String']]

# Convert embeddings list to numpy array
embeddings_array = np.vstack(embeddings_list)

# Apply UMAP dimensionality reduction
reducer = umap.UMAP(n_components=5)
embeddings_umap = reducer.fit_transform(embeddings_array)

# Print reduced embeddings
print(embeddings_umap)


[[ 6.3591847  9.1615925 12.685677  10.787446   2.130002 ]
 [ 5.954944   8.18241   13.169644   9.367811   1.2150625]
 [ 6.2813563  8.262876  12.976235   8.956627   1.360215 ]
 [ 6.065316   8.873495  13.466826   9.795278   2.7884977]
 [ 6.3125916  8.776025  13.241248  10.823458   2.091225 ]
 [ 6.704693   8.840991  13.650982   9.680932   2.3932617]
 [ 6.7971168  9.186276  13.2705345 10.7000885  2.5827773]
 [ 5.6919336  9.174658  13.626388   9.0365505  1.9618407]
 [ 5.6978874  9.57487   13.37881   10.095233   1.9707443]
 [ 6.33531    9.055444  13.808158  10.479896   2.6624243]
 [ 5.7187724  9.390086  13.302444  10.580711   2.1451933]
 [ 6.093667   8.444532  13.999041   9.261475   1.6415532]
 [ 5.8125043  8.645102  13.683688   9.745094   1.1742094]
 [ 6.8591456  8.595013  13.476519   9.2833605  1.5279989]
 [ 5.717423   8.517905  13.89678    9.317368   2.2926269]
 [ 6.3662505  9.332024  12.710955  10.139134   2.6165426]
 [ 6.5494866  9.169739  13.533355   9.048848   1.3774909]
 [ 5.9300904  

In [35]:
Z=linkage(embeddings_umap,method='ward')

In [29]:
data1

Topic  Count                                               Name  \
0      -1   3522         -1_learning_algorithms_optimization_neural   
1       0   1998            0_manifolds_manifold_curvature_elliptic   
2       1   1786  1_antiferromagnetic_magnetic_superconductivity...   
3       2   1712                  2_galaxies_galactic_galaxy_cosmic   
4       3   1570             3_neural_adversarial_learning_networks   
5       4    593             4_lasso_sparse_algorithms_optimization   
6       5    567             5_learning_reinforcement_robotic_robot   
7       6    558             6_bayesian_estimators_posterior_models   
8       7    276                  7_twitter_tweets_networks_content   
9       8    270                8_networks_nodes_communities_graphs   
10      9    264                  9_bandits_bandit_optimal_learning   
11     10    228              10_complexity_algorithms_graphs_edges   
12     11    206              11_transmit_channels_decoding_channel   
13     12    142            12_microgrid_electricity_renewable_grid   
14     13    129                    13_odometry_slam_camera_cameras   
15     14     76           14_fmri_neuroimaging_neural_neuroscience   
16     15     42        15_semantics_abstraction_programming_logics   
17     16     38                    16_players_leagues_games_sports   
18     17     15          17_melanoma_segmentation_classify_lesions   
19     18     12                 18_designs_design_optimal_criteria   

                                       Representation  \
0   [learning, algorithms, optimization, neural, o...   
1   [manifolds, manifold, curvature, elliptic, flo...   
2   [antiferromagnetic, magnetic, superconductivit...   
3   [galaxies, galactic, galaxy, cosmic, cosmologi...   
4   [neural, adversarial, learning, networks, deep...   
5   [lasso, sparse, algorithms, optimization, opti...   
6   [learning, reinforcement, robotic, robot, robo...   
7   [bayesian, estimators, posterior, models, like...   
8   [twitter, tweets, networks, content, social, r...   
9   [networks, nodes, communities, graphs, network...   
10  [bandits, bandit, optimal, learning, predictio...   
11  [complexity, algorithms, graphs, edges, vertex...   
12  [transmit, channels, decoding, channel, mimo, ...   
13  [microgrid, electricity, renewable, grid, gene...   
14  [odometry, slam, camera, cameras, pose, tracki...   
15  [fmri, neuroimaging, neural, neuroscience, bra...   
16  [semantics, abstraction, programming, logics, ...   
17  [players, leagues, games, sports, basketball, ...   
18  [melanoma, segmentation, classify, lesions, cl...   
19  [designs, design, optimal, criteria, models, a...   

                                  Representative_Docs  
0   [a most data-efficient algorithms considering ...  
1   [a geometric idea behind the method to optimal...  
2   [band topology, or global wave-function struct...  
3   [a young (~2 myr) cluster chamaeleon i was one...  
4   [humans should learn inside the continuous man...  
5   [consider a problem of estimating the low-rank...  
6   [we want to build robots that are useful insid...  
7   [approximate bayesian computation (abc) was th...  
8   [online social networks are more and more stud...  
9   [the common data mining task on networks was c...  
10  [an individual's decisions are often guided by...  
11  [given the graph $g=(v,e)$ and considering eac...  
12  [inside this paper, we develop the low-complex...  
13  [scenario generation was an important step ins...  
14  [we present the new paradigm considering real-...  
15  [brain-computer interface (bci) uses brain sig...  
16  [this article aims to achieve two goals: to sh...  
17  [during a past few years advancements inside s...  
18  [an automated method to detect and analyze a m...  
19  [inside this paper we present the new method c...

In [38]:
print(Z)

[[ 8.         10.          0.55365579  2.        ]
 [ 1.          2.          0.58358238  2.        ]
 [ 0.          4.          0.67992177  2.        ]
 [13.         16.          0.71209399  2.        ]
 [ 6.          9.          0.75779297  2.        ]
 [11.         14.          0.76447458  2.        ]
 [15.         18.          0.76793571  2.        ]
 [ 3.          5.          0.78298062  2.        ]
 [ 7.         17.          0.94762695  2.        ]
 [24.         27.          1.07151286  4.        ]
 [12.         20.          1.15326436  3.        ]
 [21.         23.          1.19696745  4.        ]
 [25.         30.          1.30384052  6.        ]
 [22.         29.          1.44688635  5.        ]
 [19.         31.          1.62478115  8.        ]
 [26.         28.          1.66649234  6.        ]
 [32.         34.          2.23074849 11.        ]
 [33.         35.          4.45884519 19.        ]]


In [30]:
def create_char_dict(n):
    my_dict = {}

    for i in range(n):
        my_dict[i] = str(i)

    return my_dict

# Example usage:
n = 19
result_dict = create_char_dict(n)
print(result_dict)


{0: '0', 1: '1', 2: '2', 3: '3', 4: '4', 5: '5', 6: '6', 7: '7', 8: '8', 9: '9', 10: '10', 11: '11', 12: '12', 13: '13', 14: '14', 15: '15', 16: '16', 17: '17', 18: '18'}


In [52]:
clusters = create_char_dict(19)
print(clusters)

for i, (cluster1, cluster2, distance, count) in enumerate(Z):
    new_cluster = clusters[cluster1] + clusters[cluster2]
    clusters[19 + i] = new_cluster

# # Convert list of strings to list of individual characters for each cluster
for key in clusters:
    if isinstance(clusters[key], str) and int(clusters[key]) >= 19:
        clusters[key] = [char for char in clusters[key]]




print(clusters)

{0: ['0'], 1: ['1'], 2: ['2'], 3: ['3'], 4: ['4'], 5: ['5'], 6: ['6'], 7: ['7'], 8: ['8'], 9: ['9'], 10: ['10'], 11: ['11'], 12: ['12'], 13: ['13'], 14: ['14'], 15: ['15'], 16: ['16'], 17: ['17'], 18: ['18']}
{0: ['0'], 1: ['1'], 2: ['2'], 3: ['3'], 4: ['4'], 5: ['5'], 6: ['6'], 7: ['7'], 8: ['8'], 9: ['9'], 10: ['10'], 11: ['11'], 12: ['12'], 13: ['13'], 14: ['14'], 15: ['15'], 16: ['16'], 17: ['17'], 18: ['18'], 19: ['8', '10'], 20: ['1', '2'], 21: ['0', '4'], 22: ['13', '16'], 23: ['6', '9'], 24: ['11', '14'], 25: ['15', '18'], 26: ['3', '5'], 27: ['7', '17'], 28: ['11', '14', '7', '17'], 29: ['12', '1', '2'], 30: ['0', '4', '6', '9'], 31: ['15', '18', '0', '4', '6', '9'], 32: ['13', '16', '12', '1', '2'], 33: ['8', '10', '15', '18', '0', '4', '6', '9'], 34: ['3', '5', '11', '14', '7', '17'], 35: ['13', '16', '12', '1', '2', '3', '5', '11', '14', '7', '17'], 36: ['8', '10', '15', '18', '0', '4', '6', '9', '13', '16', '12', '1', '2', '3', '5', '11', '14', '7', '17']}


In [53]:
clusters

{0: ['0'],
 1: ['1'],
 2: ['2'],
 3: ['3'],
 4: ['4'],
 5: ['5'],
 6: ['6'],
 7: ['7'],
 8: ['8'],
 9: ['9'],
 10: ['10'],
 11: ['11'],
 12: ['12'],
 13: ['13'],
 14: ['14'],
 15: ['15'],
 16: ['16'],
 17: ['17'],
 18: ['18'],
 19: ['8', '10'],
 20: ['1', '2'],
 21: ['0', '4'],
 22: ['13', '16'],
 23: ['6', '9'],
 24: ['11', '14'],
 25: ['15', '18'],
 26: ['3', '5'],
 27: ['7', '17'],
 28: ['11', '14', '7', '17'],
 29: ['12', '1', '2'],
 30: ['0', '4', '6', '9'],
 31: ['15', '18', '0', '4', '6', '9'],
 32: ['13', '16', '12', '1', '2'],
 33: ['8', '10', '15', '18', '0', '4', '6', '9'],
 34: ['3', '5', '11', '14', '7', '17'],
 35: ['13', '16', '12', '1', '2', '3', '5', '11', '14', '7', '17'],
 36: ['8',
  '10',
  '15',
  '18',
  '0',
  '4',
  '6',
  '9',
  '13',
  '16',
  '12',
  '1',
  '2',
  '3',
  '5',
  '11',
  '14',
  '7',
  '17']}

In [62]:
list_of_words=data1['Representation'].drop(0)

In [63]:
lists_of_words=list_of_words.to_list()

In [64]:
mapped_output = {}
output=clusters
for key, value in output.items():
    words_list = [word for char in value if int(char) < len(lists_of_words) for word in lists_of_words[int(char)]]
    mapped_output[key] = words_list

# Print the mapped output
for key, value in mapped_output.items():
    print(key, value)

0 ['manifolds', 'manifold', 'curvature', 'elliptic', 'flows', 'nonlinear', 'existence', 'flow', 'boundary', 'theorem']
1 ['antiferromagnetic', 'magnetic', 'superconductivity', 'spin', 'quantum', 'superconductors', 'superconducting', 'lattice', 'electron', 'phases']
2 ['galaxies', 'galactic', 'galaxy', 'cosmic', 'cosmological', 'stellar', 'stars', 'redshift', 'planets', 'star']
3 ['neural', 'adversarial', 'learning', 'networks', 'deep', 'recognition', 'memory', 'classification', 'models', 'trained']
4 ['lasso', 'sparse', 'algorithms', 'optimization', 'optimal', 'learning', 'clustering', 'matrix', 'gradient', 'stochastic']
5 ['learning', 'reinforcement', 'robotic', 'robot', 'robots', 'planning', 'autonomous', 'grasping', 'learn', 'control']
6 ['bayesian', 'estimators', 'posterior', 'models', 'likelihood', 'estimates', 'inference', 'approximation', 'approximate', 'learning']
7 ['twitter', 'tweets', 'networks', 'content', 'social', 'recommender', 'popularity', 'topics', 'behavior', 'rating

In [67]:
output1 = create_char_dict(19)
mapped_output = {}
for key, value in output1.items():
    words_list = [word for char in value if int(char) < len(lists_of_words) for word in lists_of_words[int(char)]]
    #generate_topic_label_prompt(words_list)
    mapped_output[key] = words_list

# Print the mapped output
for key, value in mapped_output.items():
    print(key, value)

0 ['manifolds', 'manifold', 'curvature', 'elliptic', 'flows', 'nonlinear', 'existence', 'flow', 'boundary', 'theorem']
1 ['antiferromagnetic', 'magnetic', 'superconductivity', 'spin', 'quantum', 'superconductors', 'superconducting', 'lattice', 'electron', 'phases']
2 ['galaxies', 'galactic', 'galaxy', 'cosmic', 'cosmological', 'stellar', 'stars', 'redshift', 'planets', 'star']
3 ['neural', 'adversarial', 'learning', 'networks', 'deep', 'recognition', 'memory', 'classification', 'models', 'trained']
4 ['lasso', 'sparse', 'algorithms', 'optimization', 'optimal', 'learning', 'clustering', 'matrix', 'gradient', 'stochastic']
5 ['learning', 'reinforcement', 'robotic', 'robot', 'robots', 'planning', 'autonomous', 'grasping', 'learn', 'control']
6 ['bayesian', 'estimators', 'posterior', 'models', 'likelihood', 'estimates', 'inference', 'approximation', 'approximate', 'learning']
7 ['twitter', 'tweets', 'networks', 'content', 'social', 'recommender', 'popularity', 'topics', 'behavior', 'rating

In [68]:
!nvidia-smi

Sat Apr 20 16:47:49 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   61C    P0              30W /  70W |    563MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [69]:
!lscpu

Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         46 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  2
  On-line CPU(s) list:   0,1
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Xeon(R) CPU @ 2.30GHz
    CPU family:          6
    Model:               63
    Thread(s) per core:  2
    Core(s) per socket:  1
    Socket(s):           1
    Stepping:            0
    BogoMIPS:            4599.99
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clf
                         lush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_
                         good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fm
                         a cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hyp
                         ervisor lahf_lm abm invpcid_single ssbd ibrs ibpb stibp

In [70]:
!CT_CUBLAS=1 pip install ctransformers --no-binary ctransformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 376.1/376.1 kB 2.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for ctransformers: filename=ctransformers-0.2.27-cp310-cp310-linux_x86_64.whl size=2336798 sha256=d40496edeff3d3998a5d9cb3f9397e3efa44f915b35980a6e540446210da89a3
  Stored in directory: /root/.cache/pip/wheels/dd/54/e9/32364da8eee84a2b0b412394983c15add18816c507e90f02d8
Successfully built ctransformers


In [72]:
model_id = "TheBloke/Llama-2-7B-chat-GGML"
from ctransformers import AutoModelForCausalLM

config = {'max_new_tokens': 256, 'repetition_penalty': 1.1, 'temperature': 0.1, 'stream': True}

llm = AutoModelForCausalLM.from_pretrained(model_id,
                                           model_type="llama",
                                           #lib='avx2', for cpu use
                                           gpu_layers=110, #110 for 7b, 130 for 13b
                                           **config
                                           )

Fetching 1 files:   0%|          | 0/1 [00:00<?, ?it/s]

config.json:   0%|          | 0.00/29.0 [00:00<?, ?B/s]

Fetching 1 files:   0%|          | 0/1 [00:00<?, ?it/s]

llama-2-7b-chat.ggmlv3.q2_K.bin:   0%|          | 0.00/2.87G [00:00<?, ?B/s]

In [74]:
prompt="""Write a poem to help me remember the first 10 elements on the periodic table, giving each
element its own line."""

In [75]:
tokens = llm.tokenize(prompt)

In [77]:
llm(prompt, stream=False)

'\n\nI. Hydrogen (H)\nII. Helium (He)\nIII. Lithium (Li)\nIV. Beryllium (Be)\nV. Boron (B)\nVI. Carbon (C)\nVII. Nitrogen (N)\nVIII. Oxygen (O)\nIX. Fluorine (F)\nX. Neon (Ne)\n\nI hope this helps!'

In [78]:
# LlAMA-2-7b-chat execution
import time
start = time.time()
NUM_TOKENS=0
print('-'*4+'Start Generation'+'-'*4)
for token in llm.generate(tokens):
    print(llm.detokenize(token), end='', flush=True)
    NUM_TOKENS+=1
time_generate = time.time() - start
print('\n')
print('-'*4+'End Generation'+'-'*4)
print(f'Num of generated tokens: {NUM_TOKENS}')
print(f'Time for complete generation: {time_generate}s')
print(f'Tokens per secound: {NUM_TOKENS/time_generate}')
print(f'Time per token: {(time_generate/NUM_TOKENS)*1000}ms')

----Start Generation----


I. Hydrogen (H)
II. Helium (He)
III. Lithium (Li)
IV. Beryllium (Be)
V. Boron (B)
VI. Carbon (C)
VII. Nitrogen (N)
VIII. Oxygen (O)
IX. Fluorine (F)
X. Neon (Ne)

I hope this helps!

----End Generation----
Num of generated tokens: 98
Time for complete generation: 10.654500722885132s
Tokens per secound: 9.197990834943843
Time per token: 108.71939513148094ms


In [79]:
def generate_topic_label_prompt(word_set):
    # Convert the word set to a list for formatting
    word_list = list(word_set)

    # Create the prompt string
    prompt = f"Given the following set of words, provide a clear and succinct topic label that encapsulates the overall theme or subject represented by these words. Ensure that the label stands out distinctly from any other information provided.\nAlso ensure that nothing other than the topic label is printed.:\n{word_list}"

    return prompt

In [80]:
output1

{0: ['0'],
 1: ['1'],
 2: ['2'],
 3: ['3'],
 4: ['4'],
 5: ['5'],
 6: ['6'],
 7: ['7'],
 8: ['8'],
 9: ['9'],
 10: ['10'],
 11: ['11'],
 12: ['12'],
 13: ['13'],
 14: ['14'],
 15: ['15'],
 16: ['16'],
 17: ['17'],
 18: ['18']}

In [81]:
mapped_output

{0: ['manifolds',
  'manifold',
  'curvature',
  'elliptic',
  'flows',
  'nonlinear',
  'existence',
  'flow',
  'boundary',
  'theorem'],
 1: ['antiferromagnetic',
  'magnetic',
  'superconductivity',
  'spin',
  'quantum',
  'superconductors',
  'superconducting',
  'lattice',
  'electron',
  'phases'],
 2: ['galaxies',
  'galactic',
  'galaxy',
  'cosmic',
  'cosmological',
  'stellar',
  'stars',
  'redshift',
  'planets',
  'star'],
 3: ['neural',
  'adversarial',
  'learning',
  'networks',
  'deep',
  'recognition',
  'memory',
  'classification',
  'models',
  'trained'],
 4: ['lasso',
  'sparse',
  'algorithms',
  'optimization',
  'optimal',
  'learning',
  'clustering',
  'matrix',
  'gradient',
  'stochastic'],
 5: ['learning',
  'reinforcement',
  'robotic',
  'robot',
  'robots',
  'planning',
  'autonomous',
  'grasping',
  'learn',
  'control'],
 6: ['bayesian',
  'estimators',
  'posterior',
  'models',
  'likelihood',
  'estimates',
  'inference',
  'approximation',


In [82]:
mapped_output = {}
prompts=[]
for key, value in output1.items():
    words_list = [word for char in value if int(char) < len(lists_of_words) for word in lists_of_words[int(char)]]
    pr=generate_topic_label_prompt(words_list)
    #print(pr)
    prompts.append(pr)
    mapped_output[key] = words_list

# Print the mapped output
for pr in prompts:
  print(pr)
for key, value in mapped_output.items():
    pass
    #print(key, value)

Given the following set of words, provide a clear and succinct topic label that encapsulates the overall theme or subject represented by these words. Ensure that the label stands out distinctly from any other information provided.
Also ensure that nothing other than the topic label is printed.:
['manifolds', 'manifold', 'curvature', 'elliptic', 'flows', 'nonlinear', 'existence', 'flow', 'boundary', 'theorem']
Given the following set of words, provide a clear and succinct topic label that encapsulates the overall theme or subject represented by these words. Ensure that the label stands out distinctly from any other information provided.
Also ensure that nothing other than the topic label is printed.:
['antiferromagnetic', 'magnetic', 'superconductivity', 'spin', 'quantum', 'superconductors', 'superconducting', 'lattice', 'electron', 'phases']
Given the following set of words, provide a clear and succinct topic label that encapsulates the overall theme or subject represented by these wor

In [83]:
topics=[]
for prompt in prompts:
  x=llm(prompt, stream=False)
  print(type(x))
  topics.append(x)
  print(x)

<class 'str'>


Topic Label: Geometry and Differential Equations
<class 'str'>


Topic Label: Magnetism and Superconductivity
<class 'str'>


Topic Label: Galaxies
<class 'str'>


Topic Label: Neural Networks
<class 'str'>


Topic Label: Machine Learning
<class 'str'>


Topic Label: Robotics
<class 'str'>


Topic Label: Bayesian Inference and Learning
<class 'str'>


Topic Label: Social Networking
<class 'str'>


Topic Label: Networks
<class 'str'>


Topic Label: Optimization and Learning
<class 'str'>


Topic Label: Graph Theory
<class 'str'>


Topic Label: Wireless Communication
<class 'str'>

The topic label for this set of words could be:
'Renewable Energy Systems'.
<class 'str'>


Topic Label: Robotics and 3D Mapping
<class 'str'>


Topic Label: Neuroimaging
<class 'str'>


Topic Label:
Semantic Reasoning
<class 'str'>


Topic Label: Sports
<class 'str'>

The topic label for this set of words is: Skin Cancer Detection.
<class 'str'>


Topic Label: Data Modeling and Optimization


In [84]:
print(topics)

['\n\nTopic Label: Geometry and Differential Equations', '\n\nTopic Label: Magnetism and Superconductivity', '\n\nTopic Label: Galaxies', '\n\nTopic Label: Neural Networks', '\n\nTopic Label: Machine Learning', '\n\nTopic Label: Robotics', '\n\nTopic Label: Bayesian Inference and Learning', '\n\nTopic Label: Social Networking', '\n\nTopic Label: Networks', '\n\nTopic Label: Optimization and Learning', '\n\nTopic Label: Graph Theory', '\n\nTopic Label: Wireless Communication', "\nThe topic label for this set of words could be:\n'Renewable Energy Systems'.", '\n\nTopic Label: Robotics and 3D Mapping', '\n\nTopic Label: Neuroimaging', '\n\nTopic Label:\nSemantic Reasoning', '\n\nTopic Label: Sports', '\nThe topic label for this set of words is: Skin Cancer Detection.', '\n\nTopic Label: Data Modeling and Optimization']


In [94]:
def extract_value(text):
    """
    Extracts the value following the first occurrence of ':' in a given text.

    Parameters:
    - text (str): The text from which to extract the value.

    Returns:
    - str: The extracted value, stripped of leading and trailing whitespace.
    """
    # Find the index of the first occurrence of ':'
    colon_index = text.find(':')
    if colon_index == -1:
        return text  # ':' not found

    # Calculate the start of the value by adding 1 to the index of ':'
    value_start_index = colon_index + 1

    # Extract the substring from the value's start index to the end of the text
    value = text[value_start_index:]

    # Strip leading and trailing whitespace and return the value
    return value.strip()

# Example usage:
text = "\n\nTopic Label: Graph Algorithms"
value = extract_value(text)
print(f"Extracted Value: '{value}'")

text = "\n\nTopic: Graph Algorithms"
value = extract_value(text)
print(f"Extracted Value: '{value}'")


Extracted Value: 'Graph Algorithms'
Extracted Value: 'Graph Algorithms'


In [96]:
label = "Label:"
topic_labels=[]
for text in topics:
  topic_labels.append(extract_value(text))

In [97]:
topic_labels

['Geometry and Differential Equations',
 'Magnetism and Superconductivity',
 'Galaxies',
 'Neural Networks',
 'Machine Learning',
 'Robotics',
 'Bayesian Inference and Learning',
 'Social Networking',
 'Networks',
 'Optimization and Learning',
 'Graph Theory',
 'Wireless Communication',
 "'Renewable Energy Systems'.",
 'Robotics and 3D Mapping',
 'Neuroimaging',
 'Semantic Reasoning',
 'Sports',
 'Skin Cancer Detection.',
 'Data Modeling and Optimization']

In [98]:
output

{0: ['0'],
 1: ['1'],
 2: ['2'],
 3: ['3'],
 4: ['4'],
 5: ['5'],
 6: ['6'],
 7: ['7'],
 8: ['8'],
 9: ['9'],
 10: ['10'],
 11: ['11'],
 12: ['12'],
 13: ['13'],
 14: ['14'],
 15: ['15'],
 16: ['16'],
 17: ['17'],
 18: ['18'],
 19: ['8', '10'],
 20: ['1', '2'],
 21: ['0', '4'],
 22: ['13', '16'],
 23: ['6', '9'],
 24: ['11', '14'],
 25: ['15', '18'],
 26: ['3', '5'],
 27: ['7', '17'],
 28: ['11', '14', '7', '17'],
 29: ['12', '1', '2'],
 30: ['0', '4', '6', '9'],
 31: ['15', '18', '0', '4', '6', '9'],
 32: ['13', '16', '12', '1', '2'],
 33: ['8', '10', '15', '18', '0', '4', '6', '9'],
 34: ['3', '5', '11', '14', '7', '17'],
 35: ['13', '16', '12', '1', '2', '3', '5', '11', '14', '7', '17'],
 36: ['8',
  '10',
  '15',
  '18',
  '0',
  '4',
  '6',
  '9',
  '13',
  '16',
  '12',
  '1',
  '2',
  '3',
  '5',
  '11',
  '14',
  '7',
  '17']}

In [101]:
topics_dict={index:topic for index,topic in enumerate(topic_labels)}
print(topics_dict)

{0: 'Geometry and Differential Equations', 1: 'Magnetism and Superconductivity', 2: 'Galaxies', 3: 'Neural Networks', 4: 'Machine Learning', 5: 'Robotics', 6: 'Bayesian Inference and Learning', 7: 'Social Networking', 8: 'Networks', 9: 'Optimization and Learning', 10: 'Graph Theory', 11: 'Wireless Communication', 12: "'Renewable Energy Systems'.", 13: 'Robotics and 3D Mapping', 14: 'Neuroimaging', 15: 'Semantic Reasoning', 16: 'Sports', 17: 'Skin Cancer Detection.', 18: 'Data Modeling and Optimization'}


In [102]:
updated_output={}
for key, value_list in output.items():
  updated_output[key]=[topics_dict[int(num)] for num in value_list]
print(updated_output)

{0: ['Geometry and Differential Equations'], 1: ['Magnetism and Superconductivity'], 2: ['Galaxies'], 3: ['Neural Networks'], 4: ['Machine Learning'], 5: ['Robotics'], 6: ['Bayesian Inference and Learning'], 7: ['Social Networking'], 8: ['Networks'], 9: ['Optimization and Learning'], 10: ['Graph Theory'], 11: ['Wireless Communication'], 12: ["'Renewable Energy Systems'."], 13: ['Robotics and 3D Mapping'], 14: ['Neuroimaging'], 15: ['Semantic Reasoning'], 16: ['Sports'], 17: ['Skin Cancer Detection.'], 18: ['Data Modeling and Optimization'], 19: ['Networks', 'Graph Theory'], 20: ['Magnetism and Superconductivity', 'Galaxies'], 21: ['Geometry and Differential Equations', 'Machine Learning'], 22: ['Robotics and 3D Mapping', 'Sports'], 23: ['Bayesian Inference and Learning', 'Optimization and Learning'], 24: ['Wireless Communication', 'Neuroimaging'], 25: ['Semantic Reasoning', 'Data Modeling and Optimization'], 26: ['Neural Networks', 'Robotics'], 27: ['Social Networking', 'Skin Cancer De

In [103]:
for k,v in updated_output.items():
  print(k,v)

0 ['Geometry and Differential Equations']
1 ['Magnetism and Superconductivity']
2 ['Galaxies']
3 ['Neural Networks']
4 ['Machine Learning']
5 ['Robotics']
6 ['Bayesian Inference and Learning']
7 ['Social Networking']
8 ['Networks']
9 ['Optimization and Learning']
10 ['Graph Theory']
11 ['Wireless Communication']
12 ["'Renewable Energy Systems'."]
13 ['Robotics and 3D Mapping']
14 ['Neuroimaging']
15 ['Semantic Reasoning']
16 ['Sports']
17 ['Skin Cancer Detection.']
18 ['Data Modeling and Optimization']
19 ['Networks', 'Graph Theory']
20 ['Magnetism and Superconductivity', 'Galaxies']
21 ['Geometry and Differential Equations', 'Machine Learning']
22 ['Robotics and 3D Mapping', 'Sports']
23 ['Bayesian Inference and Learning', 'Optimization and Learning']
24 ['Wireless Communication', 'Neuroimaging']
25 ['Semantic Reasoning', 'Data Modeling and Optimization']
26 ['Neural Networks', 'Robotics']
27 ['Social Networking', 'Skin Cancer Detection.']
28 ['Wireless Communication', 'Neuroimaging',

In [104]:
def generate_topic_label_prompt_h(word_set):
  word_list=list(word_set)
  prompt=f"Given the following labels, provide a clear and succinct topic label that encapsulates the overall theme or subject represented by these labels. Ensure that the label is hierarchically above the labels provided. Ensure that labels stand out distinctly from any other information provided.\nAlso ensure that nothing other than the topic label is printed only print the label do not provide explanations.:\n{word_list}"
  return prompt

In [107]:
generate_topic_label_prompt_h(updated_output[19])

"Given the following labels, provide a clear and succinct topic label that encapsulates the overall theme or subject represented by these labels. Ensure that the label is hierarchically above the labels provided. Ensure that labels stand out distinctly from any other information provided.\nAlso ensure that nothing other than the topic label is printed only print the label do not provide explanations.:\n['Networks', 'Graph Theory']"

In [109]:
hir_topic_labels=[]
for key in range(19,max(updated_output.keys())+1):
  value_list=updated_output[key]
  word_set=set(value_list)
  prompt=generate_topic_label_prompt_h(word_set)
  x=llm(prompt,stream=False)
  #x=llm(prompt, stream=False)
  hir_topic_labels.append(x)
  print(f"{x}")


Topic Label: Graph Theory and Networks

Explanation:
Graph theory and networks are two closely related fields of study that have numerous applications in various disciplines, including computer science, mathematics, biology, and social network analysis. Graph theory refers to the study of graphs, which are collections of nodes or vertices connected by edges, while networks refer to the study of complex systems composed of interconnected components.

Graph theory provides a framework for analyzing and modeling various types of graphs, including simple graphs, directed graphs, and weighted graphs. Networks, on the other hand, focuses on the structure and behavior of complex systems, such as social networks, transportation networks, and biological networks.

Both graph theory and networks have numerous applications in various fields, including computer science, artificial intelligence, data analysis, and machine learning. They are also used to model and analyze complex systems, such as t

In [110]:
hir_topic_labels

['\nTopic Label: Graph Theory and Networks\n\nExplanation:\nGraph theory and networks are two closely related fields of study that have numerous applications in various disciplines, including computer science, mathematics, biology, and social network analysis. Graph theory refers to the study of graphs, which are collections of nodes or vertices connected by edges, while networks refer to the study of complex systems composed of interconnected components.\n\nGraph theory provides a framework for analyzing and modeling various types of graphs, including simple graphs, directed graphs, and weighted graphs. Networks, on the other hand, focuses on the structure and behavior of complex systems, such as social networks, transportation networks, and biological networks.\n\nBoth graph theory and networks have numerous applications in various fields, including computer science, artificial intelligence, data analysis, and machine learning. They are also used to model and analyze complex systems,

In [111]:
def extract_value_same_line(label, text):
    """
    Extracts the value in the same line following a specified label in a given text.

    Parameters:
    - label (str): The label preceding the value to extract.
    - text (str): The text from which to extract the value.

    Returns:
    - str: The extracted value from the same line, stripped of leading and trailing whitespace, or None if the label is not found.
    """
    # Find the start of the label
    start_index = text.find(label)
    if start_index == -1:
        return None  # Label not found

    # Calculate the start of the value by adding the length of the label
    value_start_index = start_index + len(label)

    # Find the end of the line (newline character) starting from the label's start index
    end_of_line_index = text.find('\n', value_start_index)
    if end_of_line_index == -1:  # If no newline is found, take the rest of the text
        value = text[value_start_index:]
    else:
        # Extract the substring from the value's start index to the end of the line
        value = text[value_start_index:end_of_line_index]

    # Strip leading and trailing whitespace and return the value
    return value.strip()

# Example usage:
text = "\nTopic Label: Graph Algorithms and Optimization\n\nExplanation: This topic label encapsulates the overall theme of graph algorithms and optimization, which includes various subtopics such as graph traversal, graph partitioning, graph clustering, and optimization techniques for solving graph problems."
label = "Topic Label:"
value = extract_value_same_line(label, text)
print(f"Extracted Value: '{value}'")


Extracted Value: 'Graph Algorithms and Optimization'


In [112]:
label="Label:"
final_h_labels=[]
for h_label in hir_topic_labels:
  x=extract_value_same_line(label,h_label)
  final_h_labels.append(x)

In [113]:
final_h_labels

['Graph Theory and Networks',
 'Galaxies',
 'Mathematics',
 'Sports and Technology',
 'Bayesian Inference and Learning',
 'Neuroimaging and Wireless Communication',
 'Knowledge Representation and Reasoning',
 'Artificial Intelligence',
 'Social Media',
 'Neuroimaging',
 'Renewable Energy Systems',
 'Machine Learning',
 'Machine Learning',
 'Renewable Energy Systems.',
 'Artificial Intelligence',
 'Computational Biology',
 'Artificial Intelligence',
 'Machine Learning']

In [114]:
topic_labels

['Geometry and Differential Equations',
 'Magnetism and Superconductivity',
 'Galaxies',
 'Neural Networks',
 'Machine Learning',
 'Robotics',
 'Bayesian Inference and Learning',
 'Social Networking',
 'Networks',
 'Optimization and Learning',
 'Graph Theory',
 'Wireless Communication',
 "'Renewable Energy Systems'.",
 'Robotics and 3D Mapping',
 'Neuroimaging',
 'Semantic Reasoning',
 'Sports',
 'Skin Cancer Detection.',
 'Data Modeling and Optimization']

In [115]:
topic_labels.extend(final_h_labels)

In [116]:
topic_labels

['Geometry and Differential Equations',
 'Magnetism and Superconductivity',
 'Galaxies',
 'Neural Networks',
 'Machine Learning',
 'Robotics',
 'Bayesian Inference and Learning',
 'Social Networking',
 'Networks',
 'Optimization and Learning',
 'Graph Theory',
 'Wireless Communication',
 "'Renewable Energy Systems'.",
 'Robotics and 3D Mapping',
 'Neuroimaging',
 'Semantic Reasoning',
 'Sports',
 'Skin Cancer Detection.',
 'Data Modeling and Optimization',
 'Graph Theory and Networks',
 'Galaxies',
 'Mathematics',
 'Sports and Technology',
 'Bayesian Inference and Learning',
 'Neuroimaging and Wireless Communication',
 'Knowledge Representation and Reasoning',
 'Artificial Intelligence',
 'Social Media',
 'Neuroimaging',
 'Renewable Energy Systems',
 'Machine Learning',
 'Machine Learning',
 'Renewable Energy Systems.',
 'Artificial Intelligence',
 'Computational Biology',
 'Artificial Intelligence',
 'Machine Learning']

In [117]:
output

{0: ['0'],
 1: ['1'],
 2: ['2'],
 3: ['3'],
 4: ['4'],
 5: ['5'],
 6: ['6'],
 7: ['7'],
 8: ['8'],
 9: ['9'],
 10: ['10'],
 11: ['11'],
 12: ['12'],
 13: ['13'],
 14: ['14'],
 15: ['15'],
 16: ['16'],
 17: ['17'],
 18: ['18'],
 19: ['8', '10'],
 20: ['1', '2'],
 21: ['0', '4'],
 22: ['13', '16'],
 23: ['6', '9'],
 24: ['11', '14'],
 25: ['15', '18'],
 26: ['3', '5'],
 27: ['7', '17'],
 28: ['11', '14', '7', '17'],
 29: ['12', '1', '2'],
 30: ['0', '4', '6', '9'],
 31: ['15', '18', '0', '4', '6', '9'],
 32: ['13', '16', '12', '1', '2'],
 33: ['8', '10', '15', '18', '0', '4', '6', '9'],
 34: ['3', '5', '11', '14', '7', '17'],
 35: ['13', '16', '12', '1', '2', '3', '5', '11', '14', '7', '17'],
 36: ['8',
  '10',
  '15',
  '18',
  '0',
  '4',
  '6',
  '9',
  '13',
  '16',
  '12',
  '1',
  '2',
  '3',
  '5',
  '11',
  '14',
  '7',
  '17']}

In [118]:
# Create a new dictionary to store the updated values
updated_clusters = {key: [] for key in range(19)}

# Iterate through the original dictionary to update the values
for key, values in clusters.items():
    for value in values:
        if int(value) < 19:
            updated_clusters[int(value)].append(key)

# Print the updated dictionary
print(updated_clusters)


{0: [0, 21, 30, 31, 33, 36], 1: [1, 20, 29, 32, 35, 36], 2: [2, 20, 29, 32, 35, 36], 3: [3, 26, 34, 35, 36], 4: [4, 21, 30, 31, 33, 36], 5: [5, 26, 34, 35, 36], 6: [6, 23, 30, 31, 33, 36], 7: [7, 27, 28, 34, 35, 36], 8: [8, 19, 33, 36], 9: [9, 23, 30, 31, 33, 36], 10: [10, 19, 33, 36], 11: [11, 24, 28, 34, 35, 36], 12: [12, 29, 32, 35, 36], 13: [13, 22, 32, 35, 36], 14: [14, 24, 28, 34, 35, 36], 15: [15, 25, 31, 33, 36], 16: [16, 22, 32, 35, 36], 17: [17, 27, 28, 34, 35, 36], 18: [18, 25, 31, 33, 36]}


In [122]:
updated_clusters

{0: [0, 21, 30, 31, 33, 36],
 1: [1, 20, 29, 32, 35, 36],
 2: [2, 20, 29, 32, 35, 36],
 3: [3, 26, 34, 35, 36],
 4: [4, 21, 30, 31, 33, 36],
 5: [5, 26, 34, 35, 36],
 6: [6, 23, 30, 31, 33, 36],
 7: [7, 27, 28, 34, 35, 36],
 8: [8, 19, 33, 36],
 9: [9, 23, 30, 31, 33, 36],
 10: [10, 19, 33, 36],
 11: [11, 24, 28, 34, 35, 36],
 12: [12, 29, 32, 35, 36],
 13: [13, 22, 32, 35, 36],
 14: [14, 24, 28, 34, 35, 36],
 15: [15, 25, 31, 33, 36],
 16: [16, 22, 32, 35, 36],
 17: [17, 27, 28, 34, 35, 36],
 18: [18, 25, 31, 33, 36]}

In [121]:
topic_labels

['Geometry and Differential Equations',
 'Magnetism and Superconductivity',
 'Galaxies',
 'Neural Networks',
 'Machine Learning',
 'Robotics',
 'Bayesian Inference and Learning',
 'Social Networking',
 'Networks',
 'Optimization and Learning',
 'Graph Theory',
 'Wireless Communication',
 "'Renewable Energy Systems'.",
 'Robotics and 3D Mapping',
 'Neuroimaging',
 'Semantic Reasoning',
 'Sports',
 'Skin Cancer Detection.',
 'Data Modeling and Optimization',
 'Graph Theory and Networks',
 'Galaxies',
 'Mathematics',
 'Sports and Technology',
 'Bayesian Inference and Learning',
 'Neuroimaging and Wireless Communication',
 'Knowledge Representation and Reasoning',
 'Artificial Intelligence',
 'Social Media',
 'Neuroimaging',
 'Renewable Energy Systems',
 'Machine Learning',
 'Machine Learning',
 'Renewable Energy Systems.',
 'Artificial Intelligence',
 'Computational Biology',
 'Artificial Intelligence',
 'Machine Learning']

In [123]:
# Update the clusters1 dictionary values with the Label strings
for key, values in updated_clusters.items():
    updated_clusters[key] = [topic_labels[value] for value in values]

# Print the updated clusters1 dictionary
print(updated_clusters)


{0: ['Geometry and Differential Equations', 'Mathematics', 'Machine Learning', 'Machine Learning', 'Artificial Intelligence', 'Machine Learning'], 1: ['Magnetism and Superconductivity', 'Galaxies', 'Renewable Energy Systems', 'Renewable Energy Systems.', 'Artificial Intelligence', 'Machine Learning'], 2: ['Galaxies', 'Galaxies', 'Renewable Energy Systems', 'Renewable Energy Systems.', 'Artificial Intelligence', 'Machine Learning'], 3: ['Neural Networks', 'Artificial Intelligence', 'Computational Biology', 'Artificial Intelligence', 'Machine Learning'], 4: ['Machine Learning', 'Mathematics', 'Machine Learning', 'Machine Learning', 'Artificial Intelligence', 'Machine Learning'], 5: ['Robotics', 'Artificial Intelligence', 'Computational Biology', 'Artificial Intelligence', 'Machine Learning'], 6: ['Bayesian Inference and Learning', 'Bayesian Inference and Learning', 'Machine Learning', 'Machine Learning', 'Artificial Intelligence', 'Machine Learning'], 7: ['Social Networking', 'Social Med

In [124]:
updated_clusters

{0: ['Geometry and Differential Equations',
  'Mathematics',
  'Machine Learning',
  'Machine Learning',
  'Artificial Intelligence',
  'Machine Learning'],
 1: ['Magnetism and Superconductivity',
  'Galaxies',
  'Renewable Energy Systems',
  'Renewable Energy Systems.',
  'Artificial Intelligence',
  'Machine Learning'],
 2: ['Galaxies',
  'Galaxies',
  'Renewable Energy Systems',
  'Renewable Energy Systems.',
  'Artificial Intelligence',
  'Machine Learning'],
 3: ['Neural Networks',
  'Artificial Intelligence',
  'Computational Biology',
  'Artificial Intelligence',
  'Machine Learning'],
 4: ['Machine Learning',
  'Mathematics',
  'Machine Learning',
  'Machine Learning',
  'Artificial Intelligence',
  'Machine Learning'],
 5: ['Robotics',
  'Artificial Intelligence',
  'Computational Biology',
  'Artificial Intelligence',
  'Machine Learning'],
 6: ['Bayesian Inference and Learning',
  'Bayesian Inference and Learning',
  'Machine Learning',
  'Machine Learning',
  'Artificial In

In [127]:
type(data1)

pandas.core.frame.DataFrame

In [129]:
data1.to_csv('data1.csv', index=False)

In [132]:
data2=data1
print(data2)


    Topic  Count                                               Name  \
0      -1   3522         -1_learning_algorithms_optimization_neural   
1       0   1998            0_manifolds_manifold_curvature_elliptic   
2       1   1786  1_antiferromagnetic_magnetic_superconductivity...   
3       2   1712                  2_galaxies_galactic_galaxy_cosmic   
4       3   1570             3_neural_adversarial_learning_networks   
5       4    593             4_lasso_sparse_algorithms_optimization   
6       5    567             5_learning_reinforcement_robotic_robot   
7       6    558             6_bayesian_estimators_posterior_models   
8       7    276                  7_twitter_tweets_networks_content   
9       8    270                8_networks_nodes_communities_graphs   
10      9    264                  9_bandits_bandit_optimal_learning   
11     10    228              10_complexity_algorithms_graphs_edges   
12     11    206              11_transmit_channels_decoding_channel   
13    

In [135]:
data2['New_Column'] = [updated_clusters.get(key, []) for key in range(len(data1))]

# Display the updated data1 DataFrame
print(data2)

    Topic  Count                                               Name  \
0      -1   3522         -1_learning_algorithms_optimization_neural   
1       0   1998            0_manifolds_manifold_curvature_elliptic   
2       1   1786  1_antiferromagnetic_magnetic_superconductivity...   
3       2   1712                  2_galaxies_galactic_galaxy_cosmic   
4       3   1570             3_neural_adversarial_learning_networks   
5       4    593             4_lasso_sparse_algorithms_optimization   
6       5    567             5_learning_reinforcement_robotic_robot   
7       6    558             6_bayesian_estimators_posterior_models   
8       7    276                  7_twitter_tweets_networks_content   
9       8    270                8_networks_nodes_communities_graphs   
10      9    264                  9_bandits_bandit_optimal_learning   
11     10    228              10_complexity_algorithms_graphs_edges   
12     11    206              11_transmit_channels_decoding_channel   
13    

In [137]:
data2.to_csv('data2.csv', index=False)

In [138]:
from google.colab import files

# Download the data1.csv file
files.download('data2.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>